### ISSUE TITLE
Cloud software services copied from G10 for a G11 submission are not valid, throwing a 400 error

### ISSUE THREAD

**Issue by matthewford** [alphagov/digitalmarketplace-api#930]
When I selected the option to copy all of my services, the draft Cloud software services that were created did not allow me to update anything.

I was presented with a 400 error, which looks like this was introduced here: https://github.com/alphagov/digitalmarketplace-api/pull/919#issuecomment-494165841

I manually copied and pasted everything so not urgent, but others might be also seeing this issue.

**Comment by katstevens** [comment]
@matthewford Hi Matthew - we have a fix in place for this bug (see clarification question A23). Please get in touch with the support team at `enquiries@digitalmarketplace.service.gov.uk` if you have any urgent queries about completing your G-Cloud 11 application.
